services:
  local-chat:
    build: .
    container_name: local-chat-app
    volumes:
      - chat-data:/app/data
      - uploads-data:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_PATH=/app/data/chat.db
      - UPLOAD_DIR=/app/uploads
      - JWT_SECRET=change-this-to-a-strong-secret
      - SERVICE_NAME=Local Chat
      - MDNS_HOSTNAME=chat.local
    restart: unless-stopped
    network_mode: host  # Required for mDNS to work
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/messages"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chat-data:
    driver: local
  uploads-data:
    driver: local
